import type { Metadata } from "next";


import "./globals.css";
import { Inter } from "next/font/google";

const inter = Inter({
  subsets: ["latin"],
  variable: "--font-inter",
});

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en" className={`${inter.variable}`}>
      <body className="bg-(--bg-page) text-(--text-primary) transition-colors duration-300">
        {children}
      </body>
    </html>
  );
}


export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};


